import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { notFound } from "next/navigation";

const locales = ["en", "de"];

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
interface ParamProps {
  children: React.ReactNode;
  params: ParamProps;
}

interface ParamProps {
  locale: string;
}

export default function RootLayout({
  children,
  params: { locale },
}: ParamProps) {
  if (!locales.includes(locale as any)) notFound();

  return (
    <html lang={locale}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
